2025-02-01 10:32:04,818 ERROR: Exception on /register [POST] [in C:\Users\Teddy\Desktop\New folder\venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\Teddy\Desktop\New folder\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Teddy\Desktop\New folder\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Teddy\Desktop\New folder\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Teddy\Desktop\New folder\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Teddy\Desktop\New folder\app\routes\auth.py", line 32, in register
    user.set_password(form.password.data)
    ^^^^^^^^^^^^^^^^^
AttributeError: 'User' object has no attribute 'set_password'
2025-02-01 10:39:17,932 ERROR: Exception on /register [POST] [in C:\Users\Teddy\Desktop\New folder\venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\Teddy\Desktop\New folder\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Teddy\Desktop\New folder\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Teddy\Desktop\New folder\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Teddy\Desktop\New folder\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Teddy\Desktop\New folder\app\routes\auth.py", line 32, in register
    user.set_password(form.password.data)
    ^^^^^^^^^^^^^^^^^
AttributeError: 'User' object has no attribute 'set_password'
2025-02-01 10:39:27,095 ERROR: Exception on /register [POST] [in C:\Users\Teddy\Desktop\New folder\venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\Teddy\Desktop\New folder\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Teddy\Desktop\New folder\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Teddy\Desktop\New folder\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Teddy\Desktop\New folder\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Teddy\Desktop\New folder\app\routes\auth.py", line 32, in register
    user.set_password(form.password.data)
    ^^^^^^^^^^^^^^^^^
AttributeError: 'User' object has no attribute 'set_password'
